import { BattleNode } from '../types/battle';
import { getConnectedNodes } from './networkConstants';

/**
 * Finds the shortest path between a start node and all other nodes using Dijkstra's algorithm.
 * This is a foundational function for all path-based movement and targeting.
 *
 * @param startNodeIndex The index of the node to start the search from.
 * @param nodes The array of all nodes in the battle network.
 * @returns An object containing:
 *  - `distances`: A map of node indices to their shortest distance from the start node.
 *  - `previousNodes`: A map to reconstruct the path taken to each node.
 */
export const findShortestPaths = (
  startNodeIndex: number,
  nodes: BattleNode[],
) => {
  const distances: { [key: number]: number } = {};
  const previousNodes: { [key: number]: number | null } = {};
  const pq: { index: number; priority: number }[] = [];

  nodes.forEach((_, index) => {
    distances[index] = Infinity;
    previousNodes[index] = null;
  });

  distances[startNodeIndex] = 0;
  pq.push({ index: startNodeIndex, priority: 0 });

  while (pq.length > 0) {
    // In a real-world scenario, a min-priority queue would be more efficient.
    // For our number of nodes, sorting is perfectly acceptable.
    pq.sort((a, b) => a.priority - b.priority);
    const { index: currentIndex } = pq.shift()!;

    if (distances[currentIndex] === Infinity) {
      break; 
    }

    const connectedNodeIndices = getConnectedNodes(currentIndex);
    const currentNode = nodes[currentIndex];

    for (const neighborIndex of connectedNodeIndices) {
      const neighborNode = nodes[neighborIndex];
      // The 'cost' to travel between nodes is their direct physical distance.
      const distance = Math.sqrt(
        Math.pow(currentNode.x - neighborNode.x, 2) + 
        Math.pow(currentNode.y - neighborNode.y, 2)
      );
      
      const newDist = distances[currentIndex] + distance;

      if (newDist < distances[neighborIndex]) {
        distances[neighborIndex] = newDist;
        previousNodes[neighborIndex] = currentIndex;
        pq.push({ index: neighborIndex, priority: newDist });
      }
    }
  }

  return { distances, previousNodes };
};

/**
 * Reconstructs the shortest path from the `previousNodes` map generated by Dijkstra's.
 *
 * @param startNodeIndex The index of the starting node.
 * @param endNodeIndex The index of the ending node.
 * @param previousNodes The map of previous nodes.
 * @returns An array of node indices representing the path, or an empty array if no path exists.
 */
export const reconstructPath = (
  startNodeIndex: number,
  endNodeIndex: number,
  previousNodes: { [key: number]: number | null },
): number[] => {
  const path: number[] = [];
  let currentNodeIndex: number | null = endNodeIndex;

  while (currentNodeIndex !== null && currentNodeIndex !== startNodeIndex) {
    path.unshift(currentNodeIndex);
    currentNodeIndex = previousNodes[currentNodeIndex];
  }

  if (currentNodeIndex === startNodeIndex) {
    path.unshift(startNodeIndex);
    return path;
  }
  
  return []; // No path found
}; 