import { BattleNode } from '../types/battle';
import { getConnectedNodes, NETWORK_CONNECTIONS } from './networkConstants';

/**
 * Finds the shortest path between a start node and all other nodes using Dijkstra's algorithm.
 * This is a foundational function for all path-based movement and targeting.
 *
 * @param startNodeIndex The index of the node to start the search from.
 * @param nodes The array of all nodes in the battle network.
 * @returns An object containing:
 *  - `distances`: A map of node indices to their shortest distance from the start node.
 *  - `previousNodes`: A map to reconstruct the path taken to each node.
 */
export const findShortestPaths = (
  startNodeIndex: number,
  nodes: BattleNode[],
) => {
  const distances: { [key: number]: number } = {};
  const previousNodes: { [key: number]: number | null } = {};
  const pq: { index: number; priority: number }[] = [];

  nodes.forEach((_, index) => {
    distances[index] = Infinity;
    previousNodes[index] = null;
  });

  distances[startNodeIndex] = 0;
  pq.push({ index: startNodeIndex, priority: 0 });

  while (pq.length > 0) {
    // In a real-world scenario, a min-priority queue would be more efficient.
    // For our number of nodes, sorting is perfectly acceptable.
    pq.sort((a, b) => a.priority - b.priority);
    const { index: currentIndex } = pq.shift()!;

    if (distances[currentIndex] === Infinity) {
      break;
    }

    const connectedNodeIndices = getConnectedNodes(currentIndex);
    const currentNode = nodes[currentIndex];

    for (const neighborIndex of connectedNodeIndices) {
      const neighborNode = nodes[neighborIndex];
      // The 'cost' to travel between nodes is their direct physical distance.
      const distance = Math.sqrt(
        Math.pow(currentNode.x - neighborNode.x, 2) +
        Math.pow(currentNode.y - neighborNode.y, 2)
      );

      const newDist = distances[currentIndex] + distance;

      if (newDist < distances[neighborIndex]) {
        distances[neighborIndex] = newDist;
        previousNodes[neighborIndex] = currentIndex;
        pq.push({ index: neighborIndex, priority: newDist });
      }
    }
  }

  return { distances, previousNodes };
};

/**
 * Reconstructs the shortest path from the `previousNodes` map generated by Dijkstra's.
 *
 * @param startNodeIndex The index of the starting node.
 * @param endNodeIndex The index of the ending node.
 * @param previousNodes The map of previous nodes.
 * @returns An array of node indices representing the path, or an empty array if no path exists.
 */
export const reconstructPath = (
  startNodeIndex: number,
  endNodeIndex: number,
  previousNodes: { [key: number]: number | null },
): number[] => {
  const path: number[] = [];
  let currentNodeIndex: number | null = endNodeIndex;

  while (currentNodeIndex !== null && currentNodeIndex !== startNodeIndex) {
    path.unshift(currentNodeIndex);
    currentNodeIndex = previousNodes[currentNodeIndex];
  }

  if (currentNodeIndex === startNodeIndex) {
    path.unshift(startNodeIndex);
    return path;
  }

  return []; // No path found
};

/**
 * Validates that a movement path follows network lines exactly
 * @param path Array of node indices representing the movement path
 * @returns Object with validation results
 */
export const validateNetworkLinePath = (path: number[]): { isValid: boolean; connectionCount: number; invalidConnections: [number, number][] } => {
  if (path.length < 2) {
    return { isValid: true, connectionCount: 0, invalidConnections: [] };
  }

  let connectionCount = 0;
  const invalidConnections: [number, number][] = [];

  for (let i = 0; i < path.length - 1; i++) {
    const fromNode = path[i];
    const toNode = path[i + 1];

    // Check if this connection exists in NETWORK_CONNECTIONS
    const isValidConnection = NETWORK_CONNECTIONS.some(([from, to]) =>
      (from === fromNode && to === toNode) || (from === toNode && to === fromNode)
    );

    if (isValidConnection) {
      connectionCount++;
    } else {
      invalidConnections.push([fromNode, toNode]);
    }
  }

  const isValid = invalidConnections.length === 0;
  return { isValid, connectionCount, invalidConnections };
};

/**
 * Finds the nearest valid network line to a given position
 * @param position Current battalion position
 * @param nodes Array of all nodes
 * @returns Object with nearest line info
 */
export const findNearestNetworkLine = (
  position: { x: number; y: number },
  nodes: BattleNode[]
): { nearestLine: [number, number] | null; distance: number; nearestPoint: { x: number; y: number } | null } => {
  let nearestLine: [number, number] | null = null;
  let minDistance = Infinity;
  let nearestPoint: { x: number; y: number } | null = null;

  // Check each network connection
  for (const [fromIndex, toIndex] of NETWORK_CONNECTIONS) {
    const fromNode = nodes[fromIndex];
    const toNode = nodes[toIndex];

    if (!fromNode || !toNode) {continue;}

    // Calculate distance from position to this line segment
    const distance = distanceToLineSegment(
      position,
      { x: fromNode.x, y: fromNode.y },
      { x: toNode.x, y: toNode.y }
    );

    if (distance < minDistance) {
      minDistance = distance;
      nearestLine = [fromIndex, toIndex];

      // Calculate the nearest point on this line
      nearestPoint = nearestPointOnLineSegment(
        position,
        { x: fromNode.x, y: fromNode.y },
        { x: toNode.x, y: toNode.y }
      );
    }
  }

  return { nearestLine, distance: minDistance, nearestPoint };
};

/**
 * Calculates distance from a point to a line segment
 */
const distanceToLineSegment = (
  point: { x: number; y: number },
  lineStart: { x: number; y: number },
  lineEnd: { x: number; y: number }
): number => {
  const A = point.x - lineStart.x;
  const B = point.y - lineStart.y;
  const C = lineEnd.x - lineStart.x;
  const D = lineEnd.y - lineStart.y;

  const dot = A * C + B * D;
  const lenSq = C * C + D * D;

  if (lenSq === 0) {
    // Line segment is actually a point
    return Math.sqrt(A * A + B * B);
  }

  let param = dot / lenSq;

  let xx, yy;
  if (param < 0) {
    xx = lineStart.x;
    yy = lineStart.y;
  } else if (param > 1) {
    xx = lineEnd.x;
    yy = lineEnd.y;
  } else {
    xx = lineStart.x + param * C;
    yy = lineStart.y + param * D;
  }

  const dx = point.x - xx;
  const dy = point.y - yy;
  return Math.sqrt(dx * dx + dy * dy);
};

/**
 * Finds the nearest point on a line segment to a given point
 */
const nearestPointOnLineSegment = (
  point: { x: number; y: number },
  lineStart: { x: number; y: number },
  lineEnd: { x: number; y: number }
): { x: number; y: number } => {
  const A = point.x - lineStart.x;
  const B = point.y - lineStart.y;
  const C = lineEnd.x - lineStart.x;
  const D = lineEnd.y - lineStart.y;

  const dot = A * C + B * D;
  const lenSq = C * C + D * D;

  if (lenSq === 0) {
    return { x: lineStart.x, y: lineStart.y };
  }

  let param = dot / lenSq;

  if (param < 0) {
    return { x: lineStart.x, y: lineStart.y };
  } else if (param > 1) {
    return { x: lineEnd.x, y: lineEnd.y };
  } else {
    return {
      x: lineStart.x + param * C,
      y: lineStart.y + param * D,
    };
  }
};

/**
 * Finds the optimal path for battalion-to-battalion targeting through network nodes
 * This function handles complex scenarios where battalions are on different network lines
 * and need to traverse through intermediate nodes to reach their target
 *
 * @param startNodeIndex The starting node index
 * @param targetNodeIndex The target node index
 * @param nodes Array of all nodes in the battle network
 * @returns Object containing optimal path and debug information
 */
export const findOptimalBattalionPath = (
  startNodeIndex: number,
  targetNodeIndex: number,
  nodes: BattleNode[]
): {
  path: number[];
  distance: number;
  nodeTransitions: number;
  pathOptions: { path: number[]; distance: number; transitions: number }[];
  selectedReason: string;
} => {


  // Get all possible paths using Dijkstra's algorithm
  const { distances, previousNodes } = findShortestPaths(startNodeIndex, nodes);
  const primaryPath = reconstructPath(startNodeIndex, targetNodeIndex, previousNodes);

  // Calculate alternative paths by considering different network line approaches
  const pathOptions: { path: number[]; distance: number; transitions: number }[] = [];

  // Primary path (direct shortest path)
  if (primaryPath.length > 0) {
    const primaryDistance = distances[targetNodeIndex];
    const primaryTransitions = primaryPath.length - 1;
    pathOptions.push({
      path: primaryPath,
      distance: primaryDistance,
      transitions: primaryTransitions,
    });
  }

  // Find alternative paths through different network lines
  const alternativePaths = findAlternativePaths(startNodeIndex, targetNodeIndex, nodes);
  pathOptions.push(...alternativePaths);

  // Sort by distance first, then by number of transitions
  pathOptions.sort((a, b) => {
    if (Math.abs(a.distance - b.distance) < 0.1) {
      // If distances are very close, prefer fewer transitions
      return a.transitions - b.transitions;
    }
    return a.distance - b.distance;
  });

  const selectedPath = pathOptions[0];
  const selectedReason = pathOptions.length > 1
    ? `Selected path with ${selectedPath.transitions} transitions over ${pathOptions.length} options`
    : 'Single path available';



  return {
    path: selectedPath?.path || [],
    distance: selectedPath?.distance || 0,
    nodeTransitions: selectedPath?.transitions || 0,
    pathOptions,
    selectedReason,
  };
};

/**
 * Finds alternative paths through different network lines
 * This helps when the direct path might not be optimal due to network topology
 */
const findAlternativePaths = (
  startNodeIndex: number,
  targetNodeIndex: number,
  nodes: BattleNode[]
): { path: number[]; distance: number; transitions: number }[] => {
  const alternatives: { path: number[]; distance: number; transitions: number }[] = [];

  // Get all nodes that connect to the target node
  const targetConnections = getConnectedNodes(targetNodeIndex);

  // For each connection to the target, try finding a path through that connection
  for (const connectionNode of targetConnections) {
    if (connectionNode === startNodeIndex) {continue;} // Skip if it's the start node

    const { distances, previousNodes } = findShortestPaths(startNodeIndex, nodes);
    const pathToConnection = reconstructPath(startNodeIndex, connectionNode, previousNodes);

    if (pathToConnection.length > 0) {
      // Add the target node to complete the path
      const fullPath = [...pathToConnection, targetNodeIndex];
      const totalDistance = distances[connectionNode] +
        Math.sqrt(
          Math.pow(nodes[connectionNode].x - nodes[targetNodeIndex].x, 2) +
          Math.pow(nodes[connectionNode].y - nodes[targetNodeIndex].y, 2)
        );

      alternatives.push({
        path: fullPath,
        distance: totalDistance,
        transitions: fullPath.length - 1,
      });
    }
  }

  return alternatives;
};

/**
 * Validates that a battalion path follows network topology correctly
 * Enhanced version that provides detailed validation for complex paths
 */
export const validateBattalionPath = (
  path: number[],
  startNodeIndex: number,
  targetNodeIndex: number
): {
  isValid: boolean;
  connectionCount: number;
  invalidConnections: [number, number][];
  networkViolations: string[];
  debugInfo: any;
} => {
  const validation = validateNetworkLinePath(path);
  const networkViolations: string[] = [];

  // Additional validation for battalion paths
  if (path.length > 0) {
    if (path[0] !== startNodeIndex) {
      networkViolations.push(`Path does not start at start node ${startNodeIndex}`);
    }
    if (path[path.length - 1] !== targetNodeIndex) {
      networkViolations.push(`Path does not end at target node ${targetNodeIndex}`);
    }
  }

  const debugInfo = {
    path,
    startNodeIndex,
    targetNodeIndex,
    pathLength: path.length,
    expectedStart: startNodeIndex,
    expectedEnd: targetNodeIndex,
  };

  return {
    isValid: validation.isValid && networkViolations.length === 0,
    connectionCount: validation.connectionCount,
    invalidConnections: validation.invalidConnections,
    networkViolations,
    debugInfo,
  };
};
