import { StyleSheet } from 'react-native';
import { SIZING } from '../styles/theme';

export const createBugHuntHunterSelectionStyles = () =>
  StyleSheet.create({
    container: { flex: 1 },
    patternLayer: {
      ...StyleSheet.absoluteFillObject,
    },
    patternBeam: {
      position: 'absolute',
      width: 520,
      height: 140,
      borderRadius: 120,
    },
    patternBeamA: {
      top: -30,
      left: -150,
      transform: [{ rotate: '-18deg' }],
    },
    patternBeamB: {
      top: 220,
      right: -200,
      transform: [{ rotate: '22deg' }],
    },
    patternDot: {
      position: 'absolute',
      width: 8,
      height: 8,
      borderRadius: 4,
      borderWidth: 1,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: SIZING.spacing.md,
      paddingTop: SIZING.spacing.md,
    },
    title: { fontSize: SIZING.font.body, fontWeight: '800', letterSpacing: 1 },
    content: {
      padding: SIZING.spacing.md,
      paddingBottom: SIZING.spacing.lg,
      gap: SIZING.spacing.md,
    },
    bugIntelCard: {
      borderWidth: 1,
      borderRadius: 14,
      padding: SIZING.spacing.md,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: SIZING.spacing.sm,
    },
    bugIntelLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: SIZING.spacing.sm,
    },
    bugImage: { width: 68, height: 68 },
    bugTextWrap: { flex: 1, gap: 2 },
    bugLabel: { fontSize: SIZING.font.small, letterSpacing: 1, fontWeight: '700' },
    bugTitle: { fontSize: SIZING.font.body, fontWeight: '800' },
    bugMeta: { fontSize: SIZING.font.small },
    bugTypeChip: {
      borderWidth: 1,
      minWidth: 108,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      paddingHorizontal: SIZING.spacing.sm,
      paddingVertical: SIZING.spacing.xs,
      gap: 2,
    },
    bugTypeLabel: { fontSize: SIZING.font.small, fontWeight: '800' },
    bugWeakness: { fontSize: SIZING.font.small - 1 },
    slotStrip: {
      flexDirection: 'row',
      gap: SIZING.spacing.xs,
    },
    slotCell: {
      flex: 1,
      minHeight: 58,
      borderWidth: 2,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
    },
    slotIndex: { fontSize: SIZING.font.body, fontWeight: '800' },
    slotState: { fontSize: SIZING.font.small - 2, fontWeight: '700', letterSpacing: 0.6 },
    battleIntelCard: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: SIZING.spacing.md,
      paddingVertical: SIZING.spacing.sm,
      gap: 4,
    },
    battleIntelTitle: { fontSize: SIZING.font.small, fontWeight: '800', letterSpacing: 0.8 },
    battleIntelRow: { fontSize: SIZING.font.small, fontWeight: '600' },
    battleIntelHint: { fontSize: SIZING.font.small - 1 },
    rosterPanel: {
      borderWidth: 1,
      borderRadius: 12,
      padding: SIZING.spacing.sm,
      gap: SIZING.spacing.sm,
    },
    rosterTitle: { fontSize: SIZING.font.body, fontWeight: '800', letterSpacing: 0.7 },
    hunterOptionCard: {
      borderWidth: 1,
      borderRadius: 10,
      padding: SIZING.spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: SIZING.spacing.sm,
    },
    hunterImage: { width: 74, height: 74 },
    hunterOptionMeta: { flex: 1, gap: 2 },
    hunterName: { fontSize: SIZING.font.body, fontWeight: '700' },
    hunterType: { fontSize: SIZING.font.small, fontWeight: '700' },
    hunterHint: { fontSize: SIZING.font.small - 1 },
    lockedRosterText: { fontSize: SIZING.font.small },
    huntButton: {
      marginTop: SIZING.spacing.xs,
      borderRadius: 8,
      paddingVertical: SIZING.spacing.sm,
      alignItems: 'center',
    },
    huntButtonText: { fontWeight: '800' },
  });
