import { StyleSheet } from 'react-native';
import { SIZING } from '../../../styles/theme';

export const createStyles = (colors: any) => StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.themeMode === 'light' ? 'rgba(0, 0, 0, 0.4)' : 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: colors.themeMode === 'light' ? 'rgba(245, 245, 220, 0.95)' : 'rgba(10, 10, 10, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.secondary,
    padding: SIZING.spacing.lg,
    position: 'relative',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  title: {
    color: colors.secondary,
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: SIZING.spacing.xs,
  },
  battalionName: {
    color: colors.themeMode === 'light' ? 'rgba(0, 0, 0, 0.7)' : 'rgba(255, 255, 255, 0.7)',
    fontSize: 24,
    textAlign: 'center',
    marginBottom: SIZING.spacing.md,
  },
  botTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: SIZING.spacing.sm,
    marginBottom: SIZING.spacing.md,
  },
  familyColumn: {
    flex: 1,
    alignItems: 'center',
    gap: SIZING.spacing.xs,
    minWidth: 0,
  },
  familyColumnTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: SIZING.spacing.xs,
  },
  familyDropdown: {
    width: '100%',
    minHeight: 44,
    paddingVertical: SIZING.spacing.sm,
    paddingHorizontal: SIZING.spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
  },
  familyDropdownText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  pickerOverlayRoot: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20000,
    elevation: 20000,
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  pickerSheet: {
    width: '72%',
    maxWidth: 420,
    maxHeight: '70%',
    borderRadius: 12,
    borderWidth: 1,
    padding: SIZING.spacing.md,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: SIZING.spacing.sm,
  },
  pickerScroll: {
    maxHeight: 280,
  },
  pickerOption: {
    paddingVertical: SIZING.spacing.sm,
    paddingHorizontal: SIZING.spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  pickerOptionText: {
    fontSize: 14,
    fontWeight: '500',
  },
  pickerOptionSub: {
    fontSize: 12,
    marginTop: 2,
  },
  quantityContainer: {
    marginBottom: SIZING.spacing.md,
  },
  deployButton: {
    backgroundColor: colors.themeMode === 'light' ? 'rgba(71, 23, 246, 0.08)' : 'rgba(71, 23, 246, 0.1)',
    borderWidth: 1,
    borderColor: colors.secondary,
    borderRadius: 8,
    padding: SIZING.spacing.sm,
    alignItems: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  deployButtonText: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  deployButtonDisabled: {
    borderColor: colors.themeMode === 'light' ? 'rgba(71, 23, 246, 0.3)' : 'rgba(71, 23, 246, 0.3)',
    backgroundColor: colors.themeMode === 'light' ? 'rgba(245, 245, 220, 0.95)' : 'rgba(10, 10, 10, 0.95)',
  },
  deployButtonTextDisabled: {
    color: colors.themeMode === 'light' ? 'rgba(71, 23, 246, 0.3)' : 'rgba(71, 23, 246, 0.3)',
  },
});
